### ISSUE TITLE
React SSR window undefined

### ISSUE THREAD

**Issue by nathanloisel** [viktorbergehall/perf-hoc#1]
Hey,

When running this HOC on server, i got : 
`ReferenceError: window is not defined
    at /myproject/node_modules/lc-hoc/dist/lcHOC.js:1:8288
`
I can be usefull to make it compatible with SSR.

**Comment by viktorbergehall** [comment]
I haven't really worked much with server side rendering so if anyone has any suggestions on how to fix this please submit a pull request. I guess it's a webpack config thing

**Comment by nathanloisel** [comment]
I'll try (if I have time) to make a pull request to fix it this week ;)

**Comment by nathanloisel** [comment]
I made a [PR](https://github.com/viktorbergehall/lcHOC/pull/2) (a bit later than expected) to fix it.
Waiting for feedbacks ;)

**Comment by viktorbergehall** [comment]
Please have a look at the 2.0 release
